name: Windows-x86_64

on: [push]

# Cancel any other build tasks running right now to prevent stale uploads
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'llvm/llvm-project'
        submodules: true
    - name: Build LLVM
      shell: bash
      run: mkdir target && cd target && cmake -DCMAKE_SYSTEM_NAME=Generic -DHAVE_PTHREAD_AFFINITY=0 -DLLVM_HOST_TRIPLE=x86_64-pc-windows -DLLVM_TARGETS_TO_BUILD=X86 -DCMAKE_BUILD_TYPE=Release ../llvm && cmake --build .
    - name: Zip LLVM
      shell: bash
      run: zip -r target.zip target/bin target/include target/lib
    - name: Publish Build
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: https://uploads.github.com/repos/BigBadE/LLVMBinaryBuilder/releases/154278535/assets
        asset_path: target.zip
        asset_name: Windows-x86_64.zip
        overwrite: true